---
- name: Make sure pymysql is present
  become: true
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Make sure pymysql is present
  become: true
  pip:
    name: pymysql
    state: present

- name: Install MySQL
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Create DB Wordpress
  mysql_db:
    name: wordpress
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
  become: true

- name: Create user wordpress
  mysql_user:
    host: '%'
    name: wordpress
    password: wordpress
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: '*.*:ALL'
    state: present
  become: true

- name: Change bind-address
  template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify:
  - restart mysql
